### ISSUE TITLE
Locally scoped class names

### ISSUE THREAD

**Issue by tcoopman** [rtfeldman/elm-stylesheets#3]
https://github.com/css-modules/css-modules has locally scoped class names by default. It would be nice if _elm-stylesheets_ has this possibility too.

(Great work btw!)

**Comment by rtfeldman** [comment]
Totally agree! :+1:

**Comment by tcoopman** [comment]
Nice work! Going to try this soon!

**Comment by rtfeldman** [comment]
There's a lot more on the mvp branch - see the PR :)
